config/routes.rb
Rails.application.routes.draw do
  resources :boards, only: [:new, :create, :show, :index] do
    resources :submissions, only: :create
  end

  root to: 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :submissions, dependent: :destroy

  validates :letters, presence: true
  validate :board_size_is_a_square_number

  def width
    Math.sqrt(letters.size).to_i
  end

  private

  def board_size_is_a_square_number
    sqrt = Math.sqrt(letters.size)

    if sqrt != sqrt.floor
      errors.add(:letters, "can't be a non-square number")
    end
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :board

  validates :word, presence: true

  def length
    word.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
  end

  def create
    redirect_to CreateBoard.new.call
  end

  def show
    @board = Board.find(params[:id])

    @validated_words = ValidateWords.new(@board.submissions, @board).call

    @board_grid = BoardPresenter.new(@board).call
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    
    SubmitWords.new(params[:submission][:words], @board).call

    redirect_to @board
  end
end

app/views/boards/index.html.erb
<div id="index">
  <h1> Welcome to Boggle </h1>

  <p>Boggle is played with a 4x4 grid of randomly assigned letters.</p>

  <p>The object is to find as many words as you can in the grid, according to the following rules.</p>
  <ul>
    <li>The letters must be adjoining in a chain, and may be adjacent horizontally, vertically, or diagonally</li>
    <li>Words must contain at least three letters</li>
    <li>No single letter tile may be used twice in the same word</li>
  </ul>

  <%= form_for :board, url: boards_path do |f| %>
    <p> Ready? </p>
    <%= f.submit 'Click to Play', class: 'new_game_button btn' %>
  <% end %>
</div>

app/views/boards/show.html.erb
<h1> KLOGGLE </h1>

<div id="words_form_container">
  <%= form_for :submission, url: board_submissions_path(board_id: @board.id) do |f| %>
    <%= f.text_area :words, size: "35x16", autofocus: true, id: "words_text_area"%>
    <%= f.submit "Submit Words", class: "submit_words_button btn" %>
  <% end %>
</div>

  <table id="board">
    <% @board_grid.each do |row| %>
      <tr>
        <% row.each do |letter| %>
            <td>
              <div class="content">
                <%= letter %>
              </div>
            </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <div id="validated_words_container">
    <div class="valid_words_table_container">
      <table id="validated_words_table">
        <tr>
          <td>
            Valid Words
          </td>
        </tr>
        <% @validated_words.valid_words.each do |word| %>
          <tr>
            <td>
              <%= word.word %> <%= word.score %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>  

    <div class="invalid_words_table_container">
      <table id="invalidated_words_table">
        <tr>
          <td>
            Invalid Words
          </td>
        </tr>
        <% @validated_words.invalid_words.each do |word| %>
          <tr>
            <td>
              <%= word.word %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="total_score_container">
      <p>
        Your Total Score: <%= @validated_words.valid_words.map { |word| word.score }.reduce(:+) || 0%>
      </p>
    </div>
</div>

  <%= form_for :board, url: boards_path do |f| %>
    <%= f.submit 'Start a New Game', class: 'new_game_button btn' %>
  <% end %>

<div class='scoring_instructions'>
  <h2> How to Score your Words </h2>

  <ul>
    <li>3 letters: 1 point</li>
    <li>4 letters: 1 points</li>
    <li>5 letters: 2 points</li>
    <li>6 letters: 3 points</li>
    <li>7 letters: 5 points</li>
    <li>8 or more letters : 11 points</li>
  </ul>
    
  <p>Note:</p>
  <ul>
    <li>Qu can be used as 1 or both letters, and counts as 2 letters in your word</li>
    <li>Any word found in the dictionary is valid</li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoggleRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>